spring:
  config:
     import:
        optional:
           configserver: http://localhost:9093

server:
   port: 2026
management:
   endpoints:
      web: 
        exposure:
           include: refresh
   

msg:HAPPY NEW YEAR 2026
